# Generated by Django 5.1.3 on 2024-11-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_importinvoice_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='stock',
            field=models.IntegerField(default=1),
        ),
    ]
