# Generated by Django 5.1.3 on 2024-11-25 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_stock_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cashboxmovement',
            name='type',
            field=models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('clear', 'Clear'), ('debt', 'Debt')], max_length=10),
        ),
    ]
