# Generated by Django 5.1.3 on 2025-01-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_cashboxmovement_deleted_at_cashbox_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='address',
            field=models.CharField(default='Andijon Uzbekistan', max_length=150),
        ),
        migrations.AddField(
            model_name='supplier',
            name='balance',
            field=models.CharField(default=0, max_length=10000000),
        ),
    ]
